version: "1.0"
indexPath: ./index
indexMode: INDEX_SPARQL
sparqlEndpoint: "https://mods.tools.dbpedia.org/sparql"
cleanIndex: true
cacheSize: 1000000
commitInterval: 100
indexFields:
  - fieldName: subject
    resourceName: resource
    fieldType: string
    query: | 
      PREFIX dc: <http://purl.org/dc/elements/1.1/>
      PREFIX prov: <http://www.w3.org/ns/prov#>
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      SELECT DISTINCT ?resource ?subject WHERE {
        GRAPH ?g {
        ?activity a <http://mods.tools.dbpedia.org/ns/demo#ApiDemoMod>;
        	prov:used ?resource .
        ?id dc:subject ?subject .
        FILTER(!isBlank(?subject))
        }
      }
  - fieldName: description
    resourceName: resource
    fieldType: string
    query: |
      PREFIX csvw: <http://www.w3.org/ns/csvw#>
      PREFIX dct: <http://purl.org/dc/terms/>
      PREFIX dc: <http://purl.org/dc/elements/1.1/>
      PREFIX prov: <http://www.w3.org/ns/prov#>
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      SELECT DISTINCT ?resource ?description WHERE {
        GRAPH ?g {
        ?activity a <http://mods.tools.dbpedia.org/ns/demo#ApiDemoMod>;
        	prov:used ?resource .
        ?id dct:description ?description .
        ?id csvw:table ?sometable .
        }
      }
  - fieldName: title
    resourceName: resource
    fieldType: string
    query: | 
      PREFIX csvw: <http://www.w3.org/ns/csvw#>
      PREFIX dct: <http://purl.org/dc/terms/>
      PREFIX dc: <http://purl.org/dc/elements/1.1/>
      PREFIX prov: <http://www.w3.org/ns/prov#>
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      SELECT DISTINCT ?resource ?title WHERE {
        GRAPH ?g {
        ?activity a <http://mods.tools.dbpedia.org/ns/demo#ApiDemoMod>;
        	prov:used ?resource .
        ?id dct:title ?title .
        ?id csvw:table ?sometable .
        }
      } 
