 PREFIX dc: <http://purl.org/dc/elements/1.1/> PREFIX prov: <http://www.w3.org/ns/prov#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> SELECT DISTINCT ?resource ?subject WHERE { ?activity a <http://mods.tools.dbpedia.org/ns/demo#ApiDemoMod>; prov:used ?resource . ?id dc:subject ?subject . # filter out the blank nodes FILTER(!isBlank(?subject)) }

